{
 "title": "Todo Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "quantidade de requisições em $interval",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_total_by_code_total[${interval}])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de requisições a cada $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "round(increase(http_requests_duration_seconds_count{unmapped=\"False\", url_path!~\"^admin.*\"}[${interval}]))",
     "legendFormat": "{{http_method}} {{url_path}} "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_duration_seconds_sum{job=\"fastapi-app\", unmapped=\"False\", url_path!~\"^admin.*\"} / http_requests_duration_seconds_count{job=\"fastapi-app\", unmapped=\"False\", url_path!~\"^admin.*\"}",
     "legendFormat": "{{http_method}} {{url_path}}"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_requests_duration_seconds_sum{job=\"fastapi-app\", unmapped=\"False\", url_path!~\"^admin.*\"} / http_requests_duration_seconds_count{job=\"fastapi-app\", unmapped=\"False\", url_path!~\"^admin.*\"}",
     "legendFormat": "{{http_method}} {{url_path}} "
    }
   ]
  }
 ]
}