# Generated by Django 4.2.7 on 2024-06-27 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_tasktype_name_alter_tasktype_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='color',
            field=models.CharField(default='ffffff', max_length=12),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='icon',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
