name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalar e configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          cd main_app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar os testes
        run: |
          cd main_app 
          pytest -s